from libs.core.constants import DEFAULT_PAGE_SIZE

FILTER_ALL = -1

LIST_GRID_COLUMNS = 3

LIST_GRID_URL_LIMIT = 14

__all__ = [
    "DEFAULT_PAGE_SIZE",
    "FILTER_ALL",
    "LIST_GRID_COLUMNS",
    "LIST_GRID_URL_LIMIT",
]
