"""init

Revision ID: 2b8ef4dbeaa3
Revises: 47a4bdea9602
Create Date: 2026-05-31 23:20:42.050667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b8ef4dbeaa3'
down_revision: Union[str, None] = '47a4bdea9602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('is_active', mysql.TINYINT(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_title', 'offers', ['title'], unique=False)
    op.create_table('partners',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('is_tracking', mysql.TINYINT(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partner_title', 'partners', ['title'], unique=False)
    op.create_table('partner_offer',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id', 'offer_id')
    )
    op.create_index('idx_partner_offer_unique', 'partner_offer', ['partner_id', 'offer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_partner_offer_unique', table_name='partner_offer')
    op.drop_table('partner_offer')
    op.drop_index('ix_partner_title', table_name='partners')
    op.drop_table('partners')
    op.drop_index('ix_offers_title', table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
