"""empty message

Revision ID: 5726f93001e3
Revises: 
Create Date: 2026-06-08 01:55:20.331712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5726f93001e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_offers',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('is_actve', mysql.TINYINT(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', 'offer_id')
    )
    op.create_index('idx_link_offers_unique', 'link_offers', ['link_id', 'offer_id', 'is_actve'], unique=True)
    op.create_table('partner_links',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id', 'link_id')
    )
    op.create_index('idx_partner_links_unique', 'partner_links', ['partner_id', 'link_id'], unique=True)
    op.drop_index(op.f('idx_partner_link_offer_unique'), table_name='partner_link_offer')
    op.drop_table('partner_link_offer')
    op.drop_index(op.f('ix_partner_utm_source'), table_name='partners')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_partner_utm_source'), 'partners', ['utm_source'], unique=False)
    op.create_table('partner_link_offer',
    sa.Column('partner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('link_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_actve', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], name=op.f('partner_link_offer_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('partner_link_offer_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('partner_link_offer_ibfk_3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id', 'link_id', 'offer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_partner_link_offer_unique'), 'partner_link_offer', ['partner_id', 'link_id', 'offer_id', 'is_actve'], unique=True)
    op.drop_index('idx_partner_links_unique', table_name='partner_links')
    op.drop_table('partner_links')
    op.drop_index('idx_link_offers_unique', table_name='link_offers')
    op.drop_table('link_offers')
    # ### end Alembic commands ###
