"""empty message

Revision ID: 609d1aafdf84
Revises: 0aa8fa3dc77f
Create Date: 2026-06-10 17:03:29.554411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '609d1aafdf84'
down_revision: Union[str, None] = '0aa8fa3dc77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('is_selected', mysql.TINYINT(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'is_selected')
    # ### end Alembic commands ###
