"""empty message

Revision ID: eae1ec7a767a
Revises: f1c13bdc8c9a
Create Date: 2026-06-05 15:59:41.990180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eae1ec7a767a'
down_revision: Union[str, None] = 'f1c13bdc8c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'is_active')
    op.drop_column('offers', 'created_at')
    op.drop_column('offers', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('offers', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('offers', sa.Column('is_active', mysql.TINYINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
