"""empty message

Revision ID: f1c13bdc8c9a
Revises: 
Create Date: 2026-06-05 15:56:52.279436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1c13bdc8c9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('wmid', sa.String(length=128), nullable=False))
    op.add_column('partners', sa.Column('utm_source', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_partner_title'), table_name='partners')
    op.create_index('ix_partner_utm_source', 'partners', ['utm_source'], unique=False)
    op.create_index('ix_partner_wmid', 'partners', ['wmid'], unique=False)
    op.drop_column('partners', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('title', mysql.VARCHAR(length=128), nullable=False))
    op.drop_index('ix_partner_wmid', table_name='partners')
    op.drop_index('ix_partner_utm_source', table_name='partners')
    op.create_index(op.f('ix_partner_title'), 'partners', ['title'], unique=False)
    op.drop_column('partners', 'utm_source')
    op.drop_column('partners', 'wmid')
    # ### end Alembic commands ###
